name: codio-publish
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Install zstd
      run: sudo apt install zstd
    
    - uses: actions/checkout@v2

    - uses: codio/codio-assessments-publish-action@master
      with:
        client-id: ${{ secrets.CODIO_CLIENT_ID }}
        secret-id: ${{ secrets.CODIO_SECRET_ID }}
        library-id: Max Library
        dir: ./
        domain: codio.com

    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Automatic commit library Ids